# When a pattern is provided a timestamp will be printed in front of each log entry line
# The pattern format support is the same as java.text.SimpleDateFormat
timestampPattern: ""

# removes the leading [INFO] from the log lines
removeLogLevel: true

coloring:
    - pattern: ".*BUILD SUCCESS"
      background: green
      foreground: white

    - pattern: ".*BUILD FAILURE"
      background: red
      foreground: white

    # highlight the start of a plugin's execution
    - pattern: ".*--- .+ ---"
      background: yellow
      foreground: white

